=== Hatulak/JavaWWW/src/main/webapp/WEB-INF/xmls/breakfastMenuXMLDocument.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="breakfast_menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="food" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="price">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="curr" type="xs:string" default="$"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="calories" type="xs:integer" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="type">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="fruits|bread|vegetables|milk"/>
                                </xs:restriction>

                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Hatulak/JavaWWW/src/main/webapp/WEB-INF/xmls/breakfastMenuXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>

<breakfast_menu xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                xsi:noNamespaceSchemaLocation='breakfastMenuXMLDocument.xsd'>
    <food type="bread"> <!-- atrybut musi wystąpić, tylko fruits|bread|milk|vegetables -->
        <name>Belgian Waffles</name> <!-- musi wystąpić -->
        <price curr="EUR">5.95</price> <!-- musi wystąpić -->
        <description> <!-- musi wystąpić min 20 znaków, max 100 znaków-->
            Two of our famous Belgian Waffles with plenty of real maple syrup
        </description>
        <calories>650</calories> <!-- brak wartości ujemnych -->
    </food>
    <food type="bread">
        <name>Strawberry Belgian Waffles</name>
        <price>7.95</price>
        <description>
            Light Belgian waffles covered with strawberries and whipped cream
        </description>
        <calories>900</calories>
    </food>
    <food type="fruits">
        <name>Strawberries</name>
        <price>4.95</price>
        <description>
            Fresh tasty strawberries
        </description>
        <calories>90</calories>
    </food>
</breakfast_menu>
